#!/usr/bin/env php
<?php

namespace Discommand2;

use Discommand2\Core\LogFactory;

$brainName = basename(__DIR__);

function requireFile(string $path)
{
    if (!file_exists($path)) throw new \Exception("Required $path not found!");
    require_once($path);
}

function autoLoad()
{
    if (!file_exists(__DIR__ . '/vendor/autoload.php')) {
        requireFile(__DIR__ . '/src/Composer.php');
        Composer::command('install') or throw new \Exception("Composer install failed!");
    }
    requireFile(__DIR__ . '/vendor/autoload.php');
    return class_exists('\Discommand2\Core\Brain');
}

try {
    autoLoad() or throw new \Exception("$brainName failed to autoload!");
    $log = LogFactory::create($brainName) or throw new \Exception("Logger failed to create!");
} catch (\Exception $e) {
    echo ("[FATAL] " . $e->getMessage() . "\n");
    exit(1);
} catch (\Throwable $e) {
    echo ("[FATAL] " . $e->getMessage() . "\n");
    exit(1);
} catch (\Error $e) {
    echo ("[FATAL] " . $e->getMessage() . "\n");
    exit(1);
}

try {
    $skull = new Skull($log, $brainName) or throw new \Exception("Unable to create $brainName's skull!");
    $skull->run($argv) or throw new \Exception("$brainName's skull failed to run!");
} catch (\Exception $e) {
    $log->debug($e->getMessage(), ["trace" => $e->getTrace()]);
    $log->error($e->getMessage());
    exit(1);
} catch (\Throwable $e) {
    $log->debug($e->getMessage(), ["trace" => $e->getTrace()]);
    $log->error($e->getMessage());
    exit(1);
} catch (\Error $e) {
    $log->debug($e->getMessage(), ["trace" => $e->getTrace()]);
    $log->error($e->getMessage());
    exit(1);
}
